export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const ACCEPT_ERROR = 'ACCEPT_ERROR';

export const GET_AIRPORTS = 'GET_AIRPORTS';
export const GET_AIRPORTS_SUCCESS= 'GET_AIRPORTS_SUCCESS';
export const GET_AIRPORTS_FAIL = 'GET_AIRPORTS_FAIL';

export const GET_AIRPORT_INFO = 'GET_AIRPORT_INFO';
export const GET_AIRPORT_INFO_SUCCESS = 'GET_AIRPORT_INFO_SUCCESS';
export const GET_AIRPORT_INFO_FAIL = 'GET_AIRPORT_INFO_FAIL';
